<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TourismDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $descriptions = [
            'Taman Kebon Rojo' => 'Taman kota yang indah dengan berbagai jenis tanaman dan tempat bersantai di pusat kota Blitar.',
            'Blitar Green Park' => 'Taman hijau dengan berbagai wahana permainan anak dan area piknik keluarga.',
            'Fish Garden Blitar' => 'Taman dengan kolam ikan yang besar dan berbagai jenis ikan hias yang menarik.',
            'Taman Pecut Kota Blitar' => 'Taman bersejarah dengan patung kuda sebagai ikon kota Blitar.',
            'Water Park Sumber Udel' => 'Wahana air dengan berbagai kolam renang dan seluncuran yang menyenangkan.',
            'Istana Gebang' => 'Rumah masa kecil Presiden Soekarno yang sekarang menjadi museum.',
            'AGROWISATA BELIMBING KARANGSARI' => 'Agrowisata dengan kebun belimbing yang luas dan produk olahan belimbing.',
            'Kampung Coklat' => 'Desa wisata dengan produksi coklat lokal dan berbagai produk olahan coklat.',
            'Bongares Wisata 3D Blitar' => 'Tempat wisata dengan mural 3D yang instagramable.',
            'Monumen Daidan PETA Blitar' => 'Monumen bersejarah yang terkait dengan perjuangan PETA di Blitar.',
            'Pantai Tambak Rejo Blitar' => 'Pantai dengan pasir putih dan pemandangan laut yang indah.',
            'Pantai Pasir Putih Pasetran Gondo Mayit' => 'Pantai dengan pasir putih yang bersih dan ombak yang tenang.',
            'Pantai Peh Pulo' => 'Pantai dengan pemandangan alam yang masih alami dan asri.',
            'Pantai pangi Warung mak guti' => 'Pantai dengan warung makan seafood yang terkenal.',
            'Pantai Pudak' => 'Pantai dengan pemandangan sunset yang menakjubkan.',
            'Pantai Jebring' => 'Pantai dengan pasir hitam dan ombak yang cocok untuk berselancar.',
            'Pantai Serang' => 'Pantai dengan pemandangan tebing dan laut yang spektakuler.',
            'Pantai Jolosutro' => 'Pantai dengan pasir putih dan air laut yang jernih.',
            'Wisata Pantai Serang' => 'Area wisata pantai dengan berbagai fasilitas pendukung.',
            'Pantai Serit' => 'Pantai dengan pemandangan alam yang masih alami.',
            'Kedung Kandang (Camping Ground Blitar)' => 'Area camping dengan pemandangan alam yang indah.',
            'Camping Ground & Cafe Puncak Sekawan' => 'Tempat camping dengan kafe yang menyajikan pemandangan spektakuler.',
            'Kalikebo Camping Ground' => 'Area camping di tengah hutan pinus yang sejuk.',
            'KALEENATA FAMILY CAMP' => 'Tempat camping yang ramah keluarga dengan berbagai fasilitas.',
            'Jamburono Camping Ground' => 'Area camping dengan pemandangan gunung dan lembah.',
            'Ngusri Camping Ground' => 'Tempat camping dengan udara sejuk dan pemandangan alam.',
            'Bumi Perkemahan Serut Blitar' => 'Area perkemahan resmi dengan fasilitas lengkap.',
            'Hutan Pinus Loji blitar' => 'Hutan pinus dengan udara sejuk dan jalur trekking.',
            'Songgo langit campground' => 'Camping ground dengan pemandangan langit malam yang indah.',
            'Loji Campervan Park' => 'Area camping khusus untuk campervan dengan fasilitas lengkap.',
            'Gunung Kelud' => 'Gunung berapi aktif dengan kawah yang menakjubkan.',
            'Gn. Umbuk' => 'Gunung dengan jalur pendakian yang menantang.',
            'Gn. Gedang' => 'Gunung dengan pemandangan alam yang masih alami.',
            'Gn. Betet' => 'Gunung dengan ketinggian sedang dan pemandangan indah.',
            'Gn. Pegat' => 'Gunung dengan jalur paralayang yang terkenal.',
            'Gunung Pegat' => 'Gunung dengan pemandangan kota Blitar dari ketinggian.',
            'Gn. Gede' => 'Gunung dengan kawah yang aktif dan pemandangan spektakuler.',
            'Gn. Butak' => 'Gunung dengan jalur pendakian yang menantang untuk petualang.',
            'Paralayang Gunung Pegat' => 'Tempat take off untuk paralayang dengan pemandangan indah.',
            'Gn. Sumedang' => 'Gunung dengan pemandangan alam yang masih asri.',
            'Makam Bung Karno' => 'Makam Proklamator Indonesia, Presiden Soekarno.',
            'Candi Penataran' => 'Kompleks candi Hindu terbesar di Jawa Timur.',
            'Situs Jatimalang' => 'Situs purbakala dengan peninggalan sejarah yang penting.',
            'Monumen Trisula' => 'Monumen yang memperingati operasi militer Trisula.',
            'Pesanggrahan Djojodigdan' => 'Bangunan bersejarah peninggalan kolonial Belanda.',
            'Candi Gedog' => 'Candi kecil dengan arsitektur khas Jawa kuno.',
            'Candi Gambar Wetan' => 'Candi dengan relief yang unik dan bersejarah.',
            'Makam Syaikh Abu Hasan Syaikh Abu Manshur Kuningan Blitar' => 'Makam ulama besar penyebar Islam di Blitar.',
            'Goa Maria Sendang Rejo' => 'Tempat ziarah umat Katolik dengan goa buatan.',
            'Masjid "Nabawi" Blitar' => 'Masjid dengan arsitektur menyerupai Masjid Nabawi di Madinah.',
            'Masjid Agung Kota Blitar' => 'Masjid utama kota Blitar dengan arsitektur megah.',
            'Makam Adipati Aryo Blitar' => 'Makam bupati pertama Blitar yang bersejarah.',
            'Masjid Ar-Rahman' => 'Masjid dengan arsitektur modern dan fasilitas lengkap.',
            'Wisata Religi Jiaroh Makam Sumberarum' => 'Tempat ziarah dengan makam-makam bersejarah.',
            'Roketto Coffee & Co Blitar' => 'Kafe dengan konsep industrial dan kopi berkualitas.',
            'Nata Coffee & Eatery' => 'Kafe dengan menu makanan dan minuman yang lengkap.',
            'Boom Cafe' => 'Kafe dengan suasana santai dan musik live.',
            'O10thic Coffee Eatery' => 'Kafe dengan desain vintage dan menu spesial.',
            'Grands Coffee' => 'Kafe dengan suasana modern dan nyaman.',
            'Tomoro Coffee - Anggrek Blitar' => 'Kafe dengan kopi spesialitas dan suasana cozy.',
            'Lak-i Coffee & Famous Pizza' => 'Kafe yang menyajikan kopi dan pizza terkenal.',
            'Tibal Coffee' => 'Kafe kecil dengan kopi racikan khusus.',
            'WANT MORE COFFEE & EATERY' => 'Kafe dengan menu makanan Barat dan kopi pilihan.',
            'Keshini Restaurant Cafe Blitar' => 'Restoran dengan menu Western dan Asian fusion.',
            'Rest Area Hand Asta Sih' => 'Area istirahat dengan fasilitas lengkap untuk wisatawan.',
            'Rest Area Bantaran' => 'Tempat istirahat dengan pemandangan alam yang indah.',
            'Pendapa Ageng Hand Asta Sih' => 'Bangunan tradisional untuk acara-acara besar.',
            'Rest Area Saung Gunung Gamping' => 'Area istirahat dengan saung dan pemandangan gunung.',
            'Rest area' => 'Tempat istirahat sederhana untuk wisatawan.',
            'Wijaya Rest Area and Parking' => 'Area parkir dan istirahat di pusat kota.',
            'Rest Area Joglo Al-Barokah' => 'Area istirahat dengan bangunan joglo tradisional.',
            'Rest Area Sumber X Bambang' => 'Tempat istirahat dengan suasana pedesaan.',
            'Rest Area Wlingi' => 'Area istirahat di daerah Wlingi dengan fasilitas lengkap.',
            'REST AREA DEWI WARNA DAN PEMANCINGAN' => 'Area istirahat dengan kolam pemancingan.',
            'Nawangwulan Guest House' => 'Penginapan dengan suasana homestay yang nyaman.',
            'Soteria' => 'Penginapan dengan desain minimalis dan modern.',
            'Irma\'Residence' => 'Guest house dengan fasilitas lengkap dan pelayanan ramah.',
            'Sans WM Hotel Blitar' => 'Hotel bintang 3 dengan fasilitas lengkap.',
            'Livy house blitar' => 'Rumah tamu dengan suasana seperti di rumah sendiri.',
            'Reddoorz Near Makam Bung Karno Blitar' => 'Hotel budget dekat Makam Bung Karno.',
            'Reddoorz New Melati near Stasiun Blitar' => 'Hotel budget dekat stasiun Blitar.',
            'AL-KISWAH SYARIAH ( Kelud Syariah ) Guest House' => 'Penginapan syariah dengan fasilitas lengkap.',
            'OYO 93976 Maluku Guest House' => 'Penginapan budget dengan standar OYO.',
            'RedDoorz @ Jalan Tanjung Blitar' => 'Hotel budget di Jalan Tanjung Blitar.',
            'Hotel Santika Blitar' => 'Hotel bintang 4 dengan fasilitas mewah.',
            'Grand Mansion Hotel Blitar' => 'Hotel dengan arsitektur megah dan pelayanan prima.',
            'Hotel Tugu Blitar' => 'Hotel dengan nuansa seni dan budaya Indonesia.',
            'Patria Palace Hotel' => 'Hotel dengan konsep keraton Jawa yang elegan.',
            'Puri Perdana Hotel & Convention Hall' => 'Hotel dengan ballroom untuk acara besar.',
            'Patria Plaza Hotel' => 'Hotel di pusat kota dengan akses mudah ke berbagai tempat.',
            'Patria Family Hotel' => 'Hotel yang ramah keluarga dengan fasilitas lengkap.',
            'Candi Sawentar' => 'Candi kecil dengan arsitektur khas Jawa Timur.',
            'Candi Simping' => 'Candi dengan relief yang unik dan bersejarah.',
            'Candi Wringin Branjang' => 'Candi dengan pohon beringin besar di sekitarnya.',
            'Candi Kotes/ Candi Papoh' => 'Candi kecil dengan nilai sejarah tinggi.',
            'Candi Kalicilik' => 'Candi dengan arsitektur sederhana namun penuh makna.',
            'Candi Mleri' => 'Candi dengan pemandangan alam yang indah di sekitarnya.',
            'Candi Sumbernanas' => 'Candi yang terletak di dekat sumber air alami.',
        ];

        $facilities = [
            'Taman Kebon Rojo' => 'Toilet, Mushola, Area Bermain Anak, Tempat Duduk, Parkir',
            'Blitar Green Park' => 'Wahana Permainan, Toilet, Mushola, Warung Makan, Parkir Luas',
            'Fish Garden Blitar' => 'Kolam Ikan, Toilet, Area Piknik, Spot Foto, Parkir',
            'Taman Pecut Kota Blitar' => 'Patung Kuda, Area Terbuka, Toilet, Tempat Duduk, Parkir',
            'Water Park Sumber Udel' => 'Kolam Renang, Seluncuran, Toilet, Mushola, Warung Makan, Parkir',
            'Istana Gebang' => 'Museum, Toilet, Guide, Spot Foto, Parkir',
            'AGROWISATA BELIMBING KARANGSARI' => 'Kebun Belimbing, Toko Oleh-oleh, Toilet, Area Piknik, Parkir',
            'Kampung Coklat' => 'Pabrik Coklat, Toko Oleh-oleh, Toilet, Spot Foto, Parkir',
            'Bongares Wisata 3D Blitar' => 'Mural 3D, Toilet, Spot Foto, Warung Makan, Parkir',
            'Monumen Daidan PETA Blitar' => 'Monumen, Toilet, Guide, Spot Foto, Parkir',
            'Pantai Tambak Rejo Blitar' => 'Pasir Putih, Toilet, Mushola, Warung Makan, Parkir',
            'Pantai Pasir Putih Pasetran Gondo Mayit' => 'Pasir Putih, Toilet, Warung Makan, Spot Foto, Parkir',
            'Pantai Peh Pulo' => 'Pemandangan Alam, Toilet Sederhana, Warung Makan, Parkir',
            'Pantai pangi Warung mak guti' => 'Warung Makan Seafood, Toilet, Spot Foto, Parkir',
            'Pantai Pudak' => 'Spot Sunset, Toilet, Warung Makan, Parkir',
            'Pantai Jebring' => 'Pasir Hitam, Toilet, Warung Makan, Spot Selancar, Parkir',
            'Pantai Serang' => 'Tebing, Toilet, Warung Makan, Spot Foto, Parkir',
            'Pantai Jolosutro' => 'Pasir Putih, Toilet, Mushola, Warung Makan, Parkir',
            'Wisata Pantai Serang' => 'Toilet, Mushola, Warung Makan, Spot Foto, Parkir Luas',
            'Pantai Serit' => 'Pemandangan Alam, Toilet Sederhana, Warung Makan, Parkir',
            'Kedung Kandang (Camping Ground Blitar)' => 'Area Camping, Toilet, Air Bersih, Spot Foto, Parkir',
            'Camping Ground & Cafe Puncak Sekawan' => 'Area Camping, Kafe, Toilet, Spot Foto, Parkir',
            'Kalikebo Camping Ground' => 'Area Camping, Toilet, Air Bersih, Spot Foto, Parkir',
            'KALEENATA FAMILY CAMP' => 'Area Camping, Toilet, Mushola, Warung Makan, Parkir',
            'Jamburono Camping Ground' => 'Area Camping, Toilet, Air Bersih, Spot Foto, Parkir',
            'Ngusri Camping Ground' => 'Area Camping, Toilet, Air Bersih, Spot Foto, Parkir',
            'Bumi Perkemahan Serut Blitar' => 'Area Camping, Toilet, Mushola, Air Bersih, Parkir',
            'Hutan Pinus Loji blitar' => 'Jalur Trekking, Toilet, Spot Foto, Parkir',
            'Songgo langit campground' => 'Area Camping, Toilet, Spot Foto, Parkir',
            'Loji Campervan Park' => 'Area Camping Khusus Campervan, Toilet, Listrik, Air Bersih, Parkir',
            'Gunung Kelud' => 'Jalur Pendakian, Pos Pendakian, Toilet, Warung Makan, Parkir',
            'Gn. Umbuk' => 'Jalur Pendakian, Toilet Sederhana, Spot Foto, Parkir',
            'Gn. Gedang' => 'Jalur Pendakian, Toilet Sederhana, Spot Foto, Parkir',
            'Gn. Betet' => 'Jalur Pendakian, Toilet Sederhana, Spot Foto, Parkir',
            'Gn. Pegat' => 'Jalur Pendakian, Area Paralayang, Toilet, Warung Makan, Parkir',
            'Gunung Pegat' => 'Jalur Pendakian, Toilet, Spot Foto, Parkir',
            'Gn. Gede' => 'Jalur Pendakian, Pos Pendakian, Toilet, Warung Makan, Parkir',
            'Gn. Butak' => 'Jalur Pendakian, Toilet Sederhana, Spot Foto, Parkir',
            'Paralayang Gunung Pegat' => 'Area Take Off Paralayang, Toilet, Warung Makan, Parkir',
            'Gn. Sumedang' => 'Jalur Pendakian, Toilet Sederhana, Spot Foto, Parkir',
            'Makam Bung Karno' => 'Area Makam, Toilet, Mushola, Museum, Parkir Luas',
            'Candi Penataran' => 'Kompleks Candi, Toilet, Guide, Spot Foto, Parkir',
            'Situs Jatimalang' => 'Area Situs, Toilet, Guide, Spot Foto, Parkir',
            'Monumen Trisula' => 'Monumen, Toilet, Spot Foto, Parkir',
            'Pesanggrahan Djojodigdan' => 'Bangunan Bersejarah, Toilet, Guide, Spot Foto, Parkir',
            'Candi Gedog' => 'Candi, Toilet, Spot Foto, Parkir',
            'Candi Gambar Wetan' => 'Candi, Toilet, Spot Foto, Parkir',
            'Makam Syaikh Abu Hasan Syaikh Abu Manshur Kuningan Blitar' => 'Area Makam, Toilet, Mushola, Parkir',
            'Goa Maria Sendang Rejo' => 'Goa, Toilet, Kapel, Spot Ziarah, Parkir',
            'Masjid "Nabawi" Blitar' => 'Masjid, Toilet, Tempat Wudhu, Parkir Luas',
            'Masjid Agung Kota Blitar' => 'Masjid, Toilet, Tempat Wudhu, Perpustakaan, Parkir Luas',
            'Makam Adipati Aryo Blitar' => 'Area Makam, Toilet, Mushola, Parkir',
            'Masjid Ar-Rahman' => 'Masjid, Toilet, Tempat Wudhu, Parkir',
            'Wisata Religi Jiaroh Makam Sumberarum' => 'Area Makam, Toilet, Mushola, Warung Makan, Parkir',
            'Roketto Coffee & Co Blitar' => 'Kafe, WiFi, Toilet, Smoking Area, Parkir',
            'Nata Coffee & Eatery' => 'Kafe, WiFi, Toilet, Smoking Area, Parkir',
            'Boom Cafe' => 'Kafe, Live Music, WiFi, Toilet, Parkir',
            'O10thic Coffee Eatery' => 'Kafe, WiFi, Toilet, Smoking Area, Parkir',
            'Grands Coffee' => 'Kafe, WiFi, Toilet, Smoking Area, Parkir',
            'Tomoro Coffee - Anggrek Blitar' => 'Kafe, WiFi, Toilet, Smoking Area, Parkir',
            'Lak-i Coffee & Famous Pizza' => 'Kafe & Restoran, WiFi, Toilet, Parkir',
            'Tibal Coffee' => 'Kafe, WiFi, Toilet, Parkir',
            'WANT MORE COFFEE & EATERY' => 'Kafe & Restoran, WiFi, Toilet, Parkir',
            'Keshini Restaurant Cafe Blitar' => 'Restoran, WiFi, Toilet, Smoking Area, Parkir',
            'Rest Area Hand Asta Sih' => 'Toilet, Mushola, Warung Makan, Tempat Istirahat, Parkir',
            'Rest Area Bantaran' => 'Toilet, Warung Makan, Tempat Istirahat, Parkir',
            'Pendapa Ageng Hand Asta Sih' => 'Gedung Serbaguna, Toilet, Parkir Luas',
            'Rest Area Saung Gunung Gamping' => 'Saung, Toilet, Warung Makan, Tempat Istirahat, Parkir',
            'Rest area' => 'Toilet Sederhana, Tempat Istirahat, Parkir',
            'Wijaya Rest Area and Parking' => 'Toilet, Tempat Istirahat, Parkir Luas',
            'Rest Area Joglo Al-Barokah' => 'Joglo, Toilet, Mushola, Warung Makan, Parkir',
            'Rest Area Sumber X Bambang' => 'Toilet, Warung Makan, Tempat Istirahat, Parkir',
            'Rest Area Wlingi' => 'Toilet, Mushola, Warung Makan, Tempat Istirahat, Parkir',
            'REST AREA DEWI WARNA DAN PEMANCINGAN' => 'Kolam Pemancingan, Toilet, Warung Makan, Parkir',
            'Nawangwulan Guest House' => 'Kamar, WiFi, Toilet, AC, Parkir',
            'Soteria' => 'Kamar, WiFi, Toilet, AC, Parkir',
            'Irma\'Residence' => 'Kamar, WiFi, Toilet, AC, Dapur, Parkir',
            'Sans WM Hotel Blitar' => 'Kamar, Restoran, WiFi, Toilet, AC, Kolam Renang, Parkir',
            'Livy house blitar' => 'Kamar, WiFi, Toilet, Dapur, Parkir',
            'Reddoorz Near Makam Bung Karno Blitar' => 'Kamar, WiFi, Toilet, AC, Parkir',
            'Reddoorz New Melati near Stasiun Blitar' => 'Kamar, WiFi, Toilet, AC, Parkir',
            'AL-KISWAH SYARIAH ( Kelud Syariah ) Guest House' => 'Kamar Syariah, WiFi, Toilet, Mushola, Parkir',
            'OYO 93976 Maluku Guest House' => 'Kamar, WiFi, Toilet, AC, Parkir',
            'RedDoorz @ Jalan Tanjung Blitar' => 'Kamar, WiFi, Toilet, AC, Parkir',
            'Hotel Santika Blitar' => 'Kamar, Restoran, WiFi, Toilet, AC, Kolam Renang, Parkir',
            'Grand Mansion Hotel Blitar' => 'Kamar, Restoran, WiFi, Toilet, AC, Kolam Renang, Ballroom, Parkir',
            'Hotel Tugu Blitar' => 'Kamar, Restoran, WiFi, Toilet, AC, Museum, Parkir',
            'Patria Palace Hotel' => 'Kamar, Restoran, WiFi, Toilet, AC, Kolam Renang, Parkir',
            'Puri Perdana Hotel & Convention Hall' => 'Kamar, Restoran, WiFi, Toilet, AC, Ballroom, Parkir',
            'Patria Plaza Hotel' => 'Kamar, Restoran, WiFi, Toilet, AC, Parkir',
            'Patria Family Hotel' => 'Kamar, Restoran, WiFi, Toilet, AC, Area Bermain Anak, Parkir',
            'Candi Sawentar' => 'Candi, Toilet, Spot Foto, Parkir',
            'Candi Simping' => 'Candi, Toilet, Spot Foto, Parkir',
            'Candi Wringin Branjang' => 'Candi, Pohon Beringin, Toilet, Spot Foto, Parkir',
            'Candi Kotes/ Candi Papoh' => 'Candi, Toilet, Spot Foto, Parkir',
            'Candi Kalicilik' => 'Candi, Toilet, Spot Foto, Parkir',
            'Candi Mleri' => 'Candi, Toilet, Spot Foto, Parkir',
            'Candi Sumbernanas' => 'Candi, Sumber Air, Toilet, Spot Foto, Parkir',
        ];

        foreach ($descriptions as $name => $desc) {
            DB::table('tourisms')
                ->where('name', $name)
                ->whereNull('description')
                ->update(['description' => $desc]);
        }

        foreach ($facilities as $name => $facil) {
            DB::table('tourisms')
                ->where('name', $name)
                ->whereNull('facilities')
                ->update(['facilities' => $facil]);
        }

        // Update untuk record yang masih memiliki NULL
        DB::table('tourisms')
            ->whereNull('description')
            ->update(['description' => 'Tempat wisata menarik di Blitar dengan pemandangan dan fasilitas yang memadai untuk pengunjung.']);

        DB::table('tourisms')
            ->whereNull('facilities')
            ->update(['facilities' => 'Toilet, Parkir, Spot Foto']);
    }
}